server:
    host: "localhost"
    port: 5002
database:
    url: mongodb://127.0.0.1:27017/catalog
auth:
    jwksUri: http://localhost:5001/.well-known/jwks.json
aws:
    s3:
        region:
        bucket:
        key:
        secret:
